i5fpga_spidrv-objs := i5fpga.o
obj-$(CONFIG_IROQ5_ADAPCL_FPGA) += i5fpga_spidrv.o

i5ds1086l_i2cdrv-objs := i5ds1086l.o
obj-$(CONFIG_IROQ5_OSC_DS1086L) += i5ds1086l_i2cdrv.o

i5ad9923a_spidrv-objs := i5ad9923a.o
obj-$(CONFIG_IROQ5_AFE_AD9923A) += i5ad9923a_spidrv.o

i5ccdhb_camera-objs := i5ccdhb.o i5ccdhb_config.o i5ccdhb_afehlpr.o i5ccdhb_v4l.o
obj-$(CONFIG_SOC_CAMERA_IROQ5_CCDHB) += i5ccdhb_camera.o  


